School.create(name: "University of California, Berkeley",
  nickname: "Berkeley",
  city: "Berkeley",
  state: "CA",
  motto: "Fiat Lux",
  email_domain: "berkeley.edu",
  undergrad_population: 27126,
  graduate_population: 10455,
  public: true,
  logo: "http://www.berkeley.edu/brand/img/seals/ucbseal_139_540.png",
  mascot: "Oski the Bear",
  date_founded: 1868)

School.create(name: "California State University, Chico",
  nickname: "Chico State",
  city: "Chico",
  state: "CA",
  motto: "Ars Probat Artificem",
  email_domain: "csuchico.edu",
  undergrad_population: 16097,
  graduate_population: 1123,
  public: true,
  logo: "https://upload.wikimedia.org/wikipedia/en/3/37/CSU_Chico_seal.png",
  mascot: "Wildcat",
  date_founded: 1887)

School.create(name: "Harvard University",
  nickname: "Harvard",
  city: "Cambridge",
  state: "MA",
  motto: "Veritas",
  email_domain: "harvard.edu",
  undergrad_population: 6700,
  graduate_population: 14500,
  public: false,
  logo: "https://upload.wikimedia.org/wikipedia/en/3/3a/Harvard_Wreath_Logo_1.svg",
  mascot: "John Harvard, the Pilgrim",
  date_founded: 1636)

School.create(name: "Leland Stanford Junior University",
  nickname: "Stanford",
  city: "Stanford",
  state: "CA",
  motto: "Die Luft der Freiheit weht",
  email_domain: "stanford.edu",
  undergrad_population: 6980,
  graduate_population: 8897,
  public: false,
  logo: "https://upload.wikimedia.org/wikipedia/en/b/b7/Stanford_University_seal_2003.svg",
  mascot: "Cardinal",
  date_founded: 1891)
